name: project-name

version: 0.1.0
license: MIT

author: author name goes here
github: githubuser/project-name

copyright: 2022 @ copyright
maintainer: maintainer@xpto.com

description: |
  project descrition
  goes here


extra-source-files:
- docs/*.md


executable:
  main: Main.hs
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  - -O3
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N


dependencies:
- base
